### ISSUE TITLE
The latest images on Dockerhub do not contain the correct php modules

### ISSUE THREAD

**Issue by ethanwayda22** [magento/magento-cloud-docker#28]
### Preconditions

1. Docker version 18.09.2, build 6247962
2. OSX: 10.14.5 (18F132)

### Steps to reproduce

1. docker pull magento/magento-cloud-docker-php:7.2-cli
2. docker run magento/magento-cloud-docker-php:7.2-cli php -m
### Expected result

1. [Screenshots, logs or description]
Starting enhanced syslogd: rsyslogd.
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gd
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

### Actual result

1. [Screenshots, logs or description]
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zlib

[Zend Modules]

**Comment by shiftedreality** [comment]
@ethanwayda22 thank you for your submission. We’ve already fixed this issue in https://github.com/magento/magento-cloud-docker/pull/27 and gonna merge this ASAP. Temporary please add PHP_EXTENSIONS variable with extensions from this PR.

**Comment by shiftedreality** [comment]
Fix merged and deployed. Closed.

**Comment by ethanwayda22** [comment]
@shiftedreality I am still not seeing the updated modules in the dockerhub image. I see the fpm was recently updated but not the cli. https://hub.docker.com/r/magento/magento-cloud-docker-php/tags

**Comment by ethanwayda22** [comment]
This was last updated 47 hours ago which is around the time of my original post. Thanks!

**Comment by YPyltiai** [comment]
@ethanwayda22 , it was updated yesterday between 11AM and 2PM Pacific. Did you try to drop your local images? It may be some caching issue.
