### ISSUE TITLE
Mailhog not catching emails in v1.3.0 / 1.3.1

### ISSUE THREAD

**Issue by Axel29** [magento/magento-cloud-docker#343]
### Preconditions
1. Use Magento Cloud Docker images on versions 1.3.0 or 1.3.1

### Steps to reproduce
1. Send email either from the admin or frontend
2. Check your emails in Mailhog

### Expected result
1. Email is catched

### Actual result
1. Mailhog is empty

### Additional information

I don't know if it is related or not but I noticed this error using `docker-compose logs --follow` while sending the email:

```
[23-Mar-2022 13:58:31] WARNING: [pool www] child 136 said into stderr: "sh: 1: /dev/null: Permission denied"
```

**Comment by BaDos** [comment]
Created the internal ticket MCLOUD-8643

**Comment by BaDos** [comment]
@Axel29 Hi,
Could you clarify which mode you are using "production" or "developer"?

**Comment by Axel29** [comment]
> @Axel29 Hi,
> Could you clarify which mode you are using "production" or "developer"?

Hi @BaDos , developer mode

**Comment by BaDos** [comment]
@Axel29 Thank you!
It will be fixed in the next release

Now you can use the workaround.
Just edit the `docker-compose.yaml` file and add the env variable `SENDMAIL_PATH` for `generic` service manually, for example:
```
generic:
    hostname: generic.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    env_file: ./.docker/config.env
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
      - 'SENDMAIL_PATH=/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025'
```

**Comment by Axel29** [comment]
Thanks for the workaround!

**Comment by BaDos** [comment]
Fixed https://github.com/magento/magento-cloud-docker/commit/4484fc98500b87bda49eeb7e5643006dbe617e50
This fix will be in the next 1.3.3 release

**Comment by Axel29** [comment]
Hi @BaDos , it doesn't seem to work with Magento 2.4.4.

I still get the following Fatal Error in my `system.log` file: 

> Laminas\Mail\Transport\Exception\RuntimeException: Unable to send mail: Unknown error in /app/vendor/laminas/laminas-mail/src/Transport/Sendmail.php:298

Here's my `docker-compose.yml` file:

```yaml
# ./vendor/bin/ece-docker 'build:compose' --with-entrypoint --with-xdebug --set-docker-host --no-os --php='8.1' --expose-db-port=3307 --mode=developer --sync-engine=native --es='7.11' --rmq='3.9'
version: '2.1'
services:
  db:
    hostname: db.magento2.docker
    image: 'mariadb:10.4'
    shm_size: 2gb
    command: --max_allowed_packet=32505856
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - '3307:3306'
    volumes:
      - '.:/app:delegated'
      - 'mymagento-magento-db:/var/lib/mysql'
      - '.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    healthcheck:
      test: 'mysqladmin ping -h localhost -pmagento2'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - db.magento2.docker
  redis:
    hostname: redis.magento2.docker
    image: 'redis:6.2'
    volumes:
      - '.:/app:delegated'
    ports:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - redis.magento2.docker
  elasticsearch:
    hostname: elasticsearch.magento2.docker
    image: 'magento/magento-cloud-docker-elasticsearch:7.11-1.3.2'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    networks:
      magento:
        aliases:
          - elasticsearch.magento2.docker
  fpm:
    hostname: fpm.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.1-fpm-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - fpm.magento2.docker
    depends_on:
      db:
        condition: service_healthy
  web:
    hostname: web.magento2.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    environment:
      - WITH_XDEBUG=1
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
    networks:
      magento:
        aliases:
          - web.magento2.docker
    depends_on:
      fpm:
        condition: service_started
  varnish:
    hostname: varnish.magento2.docker
    image: 'magento/magento-cloud-docker-varnish:6.2-1.3.2'
    networks:
      magento:
        aliases:
          - varnish.magento2.docker
    depends_on:
      web:
        condition: service_started
  tls:
    hostname: tls.magento2.docker
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.2'
    extends: generic
    networks:
      magento:
        aliases:
          - magento2.docker
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=varnish
      - UPSTREAM_PORT=80
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      varnish:
        condition: service_started
  fpm_xdebug:
    hostname: fpm_xdebug.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.1-fpm-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium xdebug'
    networks:
      magento:
        aliases:
          - fpm_xdebug.magento2.docker
    depends_on:
      db:
        condition: service_started
  generic:
    hostname: generic.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    env_file: ./.docker/config.env
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium'
  build:
    hostname: build.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento-build:
        aliases:
          - build.magento2.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  deploy:
    hostname: deploy.magento2.docker
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - deploy.magento2.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  rabbitmq:
    hostname: rabbitmq.magento2.docker
    image: 'rabbitmq:3.9'
    networks:
      magento:
        aliases:
          - rabbitmq.magento2.docker
  mailhog:
    hostname: mailhog.magento2.docker
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      - 'SENDMAIL_PATH=/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025'
    networks:
      magento:
        aliases:
          - mailhog.magento2.docker
volumes:
  mymagento-magento-db: {  }
networks:
  magento:
    driver: bridge
  magento-build:
    driver: bridge

```
